# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  - package-ecosystem: "nuget"
    directory: "/Ddth.Utilities"
    schedule:
      interval: "weekly"
      day: "saturday"
    versioning-strategy: "widen"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] # do not update to major version as it may contain breaking changes

  - package-ecosystem: "nuget"
    directory: "/Ddth.Utilities.Tests"
    schedule:
      interval: "weekly"
      day: "saturday"
    versioning-strategy: "widen"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] # do not update to major version as it may contain breaking changes
